version: '3.4'

services:
  mybuyinglist.web:
    image: ${DOCKER_REGISTRY-}mybuyinglistweb
    build:
        context: .
        dockerfile: MyBuyingList/Dockerfile
    environment:
        - ASPNETCORE_URLS=https://+:443 
    ports:
        - "8080:443"
    depends_on:
        - db
    networks:
        - buyinglist-db
    
  db:
    image: postgres:14    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - buyinglist-db

  db_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - buyinglist-db

volumes:
  postgres_data:
  
networks:
  buyinglist-db:
    # external: true
    driver: bridge