@token =
@userId = 1

PUT https://localhost:8080/api/users/{{userId}}/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "OldPassword": "Password123!",
  "NewPassword": "NewPassword123!"
}
