POST https://localhost:8080/api/Auth
Content-Type: application/json

{
  "Username": "admin",
  "Password": "Admin123\\!"
}

###

POST https://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "<refresh_token_from_login>"
}
